// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/buildings": {
            "get": {
                "description": "建物の一覧を返す。所属でフィルタリング可能。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "建物一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "返却する建物の最大数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "所属でフィルタリング",
                        "name": "affiliation",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "建物一覧",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/buildings/{building_id}": {
            "get": {
                "description": "指定した建物IDの詳細情報（写真含む）を返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "建物情報取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "建物ID",
                        "name": "building_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "建物詳細",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "パラメータ不正",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "建物が見つからない",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/get/route": {
            "get": {
                "description": "旧バージョンとの互換性のためのエンドポイント。距離のみを重みとして使用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "経路探索（レガシー）",
                "parameters": [
                    {
                        "type": "number",
                        "default": 35.181531,
                        "description": "現在地の緯度",
                        "name": "lat",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 137.109509,
                        "description": "現在地の経度",
                        "name": "lng",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "1",
                        "description": "目的地のノードID",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "経路情報",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "ノード/経路が見つからない",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "APIの健全性を確認する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "ヘルスチェック",
                "responses": {
                    "200": {
                        "description": "status と timestamp を返す",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes": {
            "get": {
                "description": "ノードの一覧を返す。ノードID・タイプ・建物ID・階数でフィルタリング可能。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "ノード一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ノードIDでフィルタリング",
                        "name": "node_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ノードタイプでフィルタリング（entrance, road, door）",
                        "name": "node_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "建物IDでフィルタリング",
                        "name": "building_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "階数でフィルタリング",
                        "name": "floor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "返却するノードの最大数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ノード一覧",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "description": "部屋の一覧を返す。建物ID・階数・部屋タイプでフィルタリング可能。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "部屋一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "建物IDでフィルタリング",
                        "name": "building_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "階数でフィルタリング",
                        "name": "floor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部屋タイプでフィルタリング（classroom, office, lab, lecture_hall）",
                        "name": "room_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "部屋一覧",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{room_id}": {
            "get": {
                "description": "指定した部屋IDの詳細情報を返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "部屋情報取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部屋ID",
                        "name": "room_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "部屋詳細",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "部屋が見つからない",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/routes/search/{building_id}": {
            "get": {
                "description": "複数の重みパラメータとフィルタリングオプションを使用した経路探索",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "経路探索",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目的地の建物ID",
                        "name": "building_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "default": 35.181531,
                        "description": "現在地の緯度",
                        "name": "lat",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 137.109509,
                        "description": "現在地の経度",
                        "name": "lng",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 3,
                        "description": "道の優先度（0:距離のみ, 1:大通り優先〜5:脇道優先）",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "階段を含む経路を許可するか",
                        "name": "stairs",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "バリアフリー経路を使用するか",
                        "name": "accessible",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "屋内優先か",
                        "name": "indoor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "経路情報",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "パラメータ不正",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "ノード/建物/経路が見つからない",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "AIT Guide API",
	Description:      "建物内外の経路情報を管理し、複数の重みパラメータを考慮した最適経路を提供するWebAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
